<a href="https://colab.research.google.com/github/Vignesh218/ML-lab-experiments/blob/main/ML_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    'Name': ["Varun","Nishad","Akshat","Saurabh"],
    'Age':[21,19,20,22],
    'City':["Kharghar","Powai","Sangli","Kalyan"]
}

df = pd.DataFrame(data)
index = [1,2,3,4]
df.index = index
print(df)
print()
cities = df['City']
cities.index = index
print(cities)

filtered = df[df['Age']>20]

print(filtered)

      Name  Age      City
1    Varun   21  Kharghar
2   Nishad   19     Powai
3   Akshat   20    Sangli
4  Saurabh   22    Kalyan

1    Kharghar
2       Powai
3      Sangli
4      Kalyan
Name: City, dtype: object
      Name  Age      City
1    Varun   21  Kharghar
4  Saurabh   22    Kalyan


In [ ]:
import numpy as np

arr1 = np.array([[2,5],[7,8]])
det = np.linalg.det(arr1)
if det != 0:
  print("It is invertible")
else:
  print("It is not invertible")



It is invertible


In [ ]:
import pandas as pd

df = pd.read_csv('/crime_dataset_india.csv')

cols_to_keep = [
    'STATE/UT',
    'YEAR',
    'POPULATION',
    'TOTAL IPC CRIMES',
    'MURDER',
    'THEFT',
    'DOWRY DEATHS'
]
df_filtered = df[cols_to_keep]

latest_year = df_filtered['YEAR'].max()
top_states = df_filtered[df_filtered['YEAR'] == latest_year].sort_values(by='TOTAL IPC CRIMES', ascending=False).head(5)
print(top_states[['STATE/UT', 'TOTAL IPC CRIMES','YEAR']])



In [ ]:
import pandas as pd
import numpy as np


file_path = '/content/drive/MyDrive/SEM 5 MATERIALS VARUN/ML LAB SEM_5/crime_dataset_india.csv'

# Read the CSV file
df = pd.read_csv(file_path)
print("Original Dataset Shape:", df.shape)

# -------------------------------------
# 🧹 Step 3: Drop Unnecessary Columns & Rows
# -------------------------------------

# Drop columns that are less useful
df_cleaned = df.drop(columns=['Report Number', 'Date Reported', 'Time of Occurrence', 'Date Case Closed'])

# Drop rows with missing essential values
df_cleaned = df_cleaned.dropna(subset=['City', 'Victim Age', 'Crime Description'])

print("Cleaned Dataset Shape:", df_cleaned.shape)
df_cleaned.head()

Original Dataset Shape: (40160, 14)
Cleaned Dataset Shape: (40160, 10)


Date of Occurrence       City  Crime Code Crime Description  Victim Age  \
0   01-01-2020 00:00  Ahmedabad         576    IDENTITY THEFT          16   
1   01-01-2020 01:00    Chennai         128          HOMICIDE          37   
2   01-01-2020 02:00   Ludhiana         271        KIDNAPPING          48   
3   01-01-2020 03:00       Pune         170          BURGLARY          49   
4   01-01-2020 04:00       Pune         421         VANDALISM          30   

  Victim Gender   Weapon Used   Crime Domain  Police Deployed Case Closed  
0             M  Blunt Object  Violent Crime               13          No  
1             M        Poison    Other Crime                9          No  
2             F  Blunt Object    Other Crime               15          No  
3             F       Firearm    Other Crime                1         Yes  
4             F         Other    Other Crime               18         Yes

In [ ]:
# PANDAS Operations #
# 1. Grouping: Crimes per city
crime_by_city = df_cleaned.groupby('City').size().sort_values(ascending=False)
print("\n1. Crimes per city:\n", crime_by_city.head())


1. Crimes per city:
 City
Delhi        5400
Mumbai       4415
Bangalore    3588
Hyderabad    2881
Kolkata      2518
dtype: int64


In [ ]:
# 2. Filtering: Cases with Weapon = Firearm
firearm_cases = df_cleaned[df_cleaned['Weapon Used'] == 'Firearm']
print("\n2. Firearm-related crimes:\n", firearm_cases.head())


2. Firearm-related crimes:
    Date of Occurrence           City  Crime Code   Crime Description  \
3    01-01-2020 03:00           Pune         170            BURGLARY   
5    01-01-2020 05:00          Delhi         442             ASSAULT   
25   01-02-2020 01:00         Jaipur         282             ASSAULT   
40   01-02-2020 16:00  Visakhapatnam         148            HOMICIDE   
48   01-03-2020 00:00         Jaipur         139  ILLEGAL POSSESSION   

    Victim Age Victim Gender Weapon Used   Crime Domain  Police Deployed  \
3           49             F     Firearm    Other Crime                1   
5           16             M     Firearm  Violent Crime               18   
25          60             M     Firearm  Violent Crime               15   
40          28             F     Firearm    Other Crime                2   
48          77             F     Firearm    Other Crime               17   

   Case Closed  
3          Yes  
5          Yes  
25         Yes  
40          N

In [ ]:
# 3. Sorting: Top police deployment
sorted_police = df_cleaned.sort_values(by='Police Deployed', ascending=False)
print("\n3. Highest police deployed:\n", sorted_police[['City', 'Police Deployed']].head())


3. Highest police deployed:
             City  Police Deployed
16918  Bangalore               19
16920     Mumbai               19
32         Delhi               19
8387   Ghaziabad               19
40113     Mumbai               19


In [ ]:
# 4. Value Counts: Case Closed stats
case_status = df_cleaned['Case Closed'].value_counts()
print("\n4. Case closure count:\n", case_status)


4. Case closure count:
 Case Closed
No     20098
Yes    20062
Name: count, dtype: int64


In [ ]:
# 5. Case Duration (in days) for closed cases
df_cleaned['Date of Occurrence'] = pd.to_datetime(df_cleaned['Date of Occurrence'], errors='coerce')
df_cleaned['Case Closed Date'] = pd.to_datetime(df['Date Case Closed'], errors='coerce', dayfirst=True)
df_cleaned['Case Duration (days)'] = (df_cleaned['Case Closed Date'] - df_cleaned['Date of Occurrence']).dt.days
print("\n5. Case Duration:\n", df_cleaned[['City', 'Case Closed', 'Case Duration (days)']].head())


5. Case Duration:
         City Case Closed  Case Duration (days)
0  Ahmedabad          No                   NaN
1    Chennai          No                   NaN
2   Ludhiana          No                   NaN
3       Pune         Yes                 119.0
4       Pune         Yes                   7.0


In [ ]:
# NUMPY Operations #
# Convert Victim Age to NumPy array
ages = df_cleaned['Victim Age'].to_numpy()

In [ ]:
# 1. Print first few elements
print("\n1. Victim Age Array:\n", ages[:5])


1. Victim Age Array:
 [16 37 48 49 30]


In [ ]:
# 2. Basic statistics
print("\n2. Age Stats:\nMean:", np.mean(ages), "\nMedian:", np.median(ages), "\nStd Dev:", np.std(ages))


2. Age Stats:
Mean: 44.49125996015936 
Median: 44.0 
Std Dev: 20.225297837502605


In [ ]:
# 3. Boolean indexing (minors)
minors = ages[ages < 18]
print("\n3. Minors (age < 18):\n", minors[:5])


3. Minors (age < 18):
 [16 16 11 16 16]


In [ ]:
# 4. Binary closed/open status
closed_array = np.where(df_cleaned['Case Closed'] == 'Yes', 1, 0)
print("\n4. Closed Cases Binary Array:\n", closed_array[:5])


4. Closed Cases Binary Array:
 [0 0 0 1 1]


In [ ]:
# 5. Normalize Victim Age
ages_norm = (ages - np.min(ages)) / (np.max(ages) - np.min(ages))
print("\n5. Normalized Victim Age:\n", ages_norm[:5])


5. Normalized Victim Age:
 [0.08695652 0.39130435 0.55072464 0.56521739 0.28985507]
